name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "8c436e9d-5ad3-4416-a201-cd1736a7aafc"
database_name = "memos-worker-notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "a88fcb6be8d341cda182b294beaa0c74"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "memos-worker-notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
